name: HelpRestored
version: 1.0
main: com.gozarproductions.HelpRestored
api-version: 1.21
description: Restores Bukkit's help.yml to Purpur.
author: Erika Gozar
website: https://gozarproductions.com
commands:
  help:
    description: Shows the help menu.
    usage: /help <topic> [page]
    permission: helprestored.use
  helpreload:
    description: Reloads help.yml and all configs.
    usage: /helpreload
    permission: helprestored.admin
permissions:
  helprestored.use:
    description: Allows use of /help
    default: true
  helprestored.admin:
    description: Allows use of /helpreload
    default: op
    children:
      helprestored.use: true