name: Delete Modrinth Release

on:
  release:
    types: [deleted]

jobs:
  delete-modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Delete corresponding Modrinth release
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "Looking for Modrinth version with tag $RELEASE_TAG"

          # Get all versions for this project
          PROJECT_ID="zE5EbgF4" # Replace with your actual project ID
          API_URL="https://api.modrinth.com/v2/project/$PROJECT_ID/version"

          VERSION_ID=$(curl -s -H "Authorization: $MODRINTH_TOKEN" "$API_URL" | \
            jq -r --arg TAG "$RELEASE_TAG" '.[] | select(.version_number == $TAG) | .id')

          if [ -z "$VERSION_ID" ]; then
            echo "No Modrinth release found for tag $RELEASE_TAG"
            exit 0
          fi

          DELETE_URL="https://api.modrinth.com/v2/version/$VERSION_ID"
          echo "Deleting Modrinth version ID: $VERSION_ID"
          curl -X DELETE "$DELETE_URL" \
            -H "Authorization: $MODRINTH_TOKEN"

          echo "Modrinth release for tag $RELEASE_TAG deleted."
