name: Upload to Modrinth

on:
  release:
    types: [published]

jobs:
  upload-to-modrinth:
    runs-on: ubuntu-latest

    steps:
      - name: Get JAR asset name from release
        id: get-jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching release info..."
          api_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}"
          asset_info=$(curl -s -H "Authorization: token $GH_TOKEN" $api_url)
          jar_name=$(echo "$asset_info" | jq -r '.assets[] | select(.name | endswith(".jar")) | .name' | head -n 1)

          if [ -z "$jar_name" ]; then
            echo "No .jar asset found in release!"
            exit 1
          fi

          echo "ASSET_NAME=$jar_name" >> $GITHUB_ENV

      - name: Download the JAR from the release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Downloading asset: $ASSET_NAME"
          asset_id=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq '.assets[] | select(.name=="'"$ASSET_NAME"'") | .id')
          curl -L -H "Authorization: token $GH_TOKEN" -H "Accept: application/octet-stream" \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id" \
            -o "$ASSET_NAME"

      - name: Prepare Modrinth metadata
        run: |
          cat <<EOF > version.json
          {
            "name": "${{ github.event.release.name }}",
            "version_number": "${{ github.ref_name }}",
            "project_id": "zE5EbgF4",
            "game_versions": ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"],
            "loaders": ["spigot", "paper", "purpur"],
            "featured": true,
            "release_channel": "release",
            "changelog": "${{ github.event.release.body }}",
            "dependencies": [
                {
                "version": "*",
                "project_id": "UmLGoGij",
                "dependency_type": "required"
                },
                {
                "version": "*",
                "project_id": "hXiIvTyT",
                "dependency_type": "required"
                }
            ],
            "file_parts": ["$ASSET_NAME"]
          }
          EOF



      - name: Upload to Modrinth via API
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          curl -X POST https://api.modrinth.com/v2/version \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "data=@version.json;type=application/json" \
            -F "file=@$ASSET_NAME;type=application/java-archive"
